name: "black-lint and static type check"

on: [push, pull_request]
# on: [workflow_call]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: setting up python env
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'

      - name: get some runtime info
        run: |
          echo PWD: $(pwd)
          echo ENV: $(env)
          echo GH-REF: ${{ github.ref }}
          echo GH-SHA: ${{ github.sha }}
          tree

      - name: installing pip-packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt

      - name: "linting with black :: check only"
        run: black -l 120 --check  vendingmachine tests

      - name: static type checking with mypy
        run: mypy vendingmachine
